### PR TITLE
Switch to yarn for nix build

### PR DESCRIPTION
**Pull request by alastairong**

### CODE REVIEW

**Comment by alastairong** [comment]
@JettTech @zo-el @robbiecarlton FYI - we need to switch to `yarn2nix` because `npmToNix` won't build holo-envoy's dependencies properly - the library is too poorly maintained. Please make sure that updated `yarn.lock` files are generated when finishing envoy stories.

**Comment by alastairong** [comment]
I don't know how to get envoy e2e tests working :(

**Review by zo-el — CHANGES_REQUESTED** [review]
You need to remove the package-lock file and also update the makefile to use yarn so that the tests pass

**Comment by alastairong** [comment]
Still failed. :(

**Review by zo-el — APPROVED** [review]
The CI is having some issues I think because of the change in hydra is causing the caching to have some issues. 

I'll merge it to the lair-shim branch so that we can handle only one branch

**Pull request merged**
