### PR TITLE
Add inbound payload size to bandwidth

### PR DESCRIPTION
**Pull request by JettTech**
### Updates:
 - adds inbound payload size to bandwidth calculation

### CODE REVIEW

**Review by zo-el — APPROVED** [review]
I think we should probably only charge for inbound_payloads about a particular size, but this is a business decision.

Else, Looks good.

**Comment by alastairong** [comment]
I'll bring this up at PL, but in general we should not charge for inbound bandwidth. This is industry standard - AWS, DO, Equinix, Azure, etc. all do the same.

That said, this may still be useful for data analysis, but if so it should be kept separate.

**Comment by alastairong** [comment]
This is approved for merging :)

**Comment by JettTech** [comment]
Deprecated by PR #144

**Pull request closed without merging**
