### PR TITLE
Conductor integration

### PR DESCRIPTION
**Pull request by mjbrisebois**

### CODE REVIEW

**Comment by zo-el** [comment]
Before starting the holochain conductor you need to create your Keystore file and also set you persistence path to an editable location on your machine (Currently it is pointed to `/var/lib/holochain-conductor`).

**Comment by zo-el** [comment]
@mjbrisebois, I just got this failing test when I run `make test-integration`

Screenshot from 2020-03-04 17-06-33

**Comment by mjbrisebois** [comment]
> @mjbrisebois, I just got this failing test when I run `make test-integration`
> 
> Screenshot from 2020-03-04 17-06-33

@zo-el Did you run conductor manually (`holochain -c conductor-1.toml`) before the integration tests?

**Comment by zo-el** [comment]
> > @mjbrisebois, I just got this failing test when I run `make test-integration`
> > Screenshot from 2020-03-04 17-06-33
> 
> @zo-el Did you run conductor manually (`holochain -c conductor-1.toml`) before the integration tests?

Yes, I did.

**Comment by zo-el** [comment]
> > > @mjbrisebois, I just got this failing test when I run `make test-integration`
> > > Screenshot from 2020-03-04 17-06-33
> > 
> > 
> > @zo-el Did you run conductor manually (`holochain -c conductor-1.toml`) before the integration tests?
> 
> @mjbrisebois Yes, I did.

Hi @mjbrisebois I figured out my mistake. I had to install the node modules first. :sweat_smile:

**Comment by zo-el** [comment]
@mjbrisebois, Now I receive this when the tests are run.
Screenshot from 2020-03-05 11-51-03

**Comment by mjbrisebois** [comment]
> @mjbrisebois, Now I receive this when the tests are run.
> Screenshot from 2020-03-05 11-51-03

@zo-el Perfect!  You are up to date then until I push the fix for https://github.com/Holo-Host/holo-envoy/issues/7

**Comment by zo-el** [comment]
K So this is the error I was trying to debug:
Screenshot from 2020-03-05 20-58-12

And It seems like the sign-up process is failing with a Timeout
Screenshot from 2020-03-06 11-43-46

And this is because the Signed payload is not able to be verified.
Here is a screenshot from the sim2h server- 
Screenshot from 2020-03-06 11-59-26

My best guess is that the crypto package that HoloCentral is using is not the same as the pkg used in Holochain.

And because of this failure (the first mentioned error), it seems to be using the anonymous user which does not have an instance in the conductor. Which is why we get the capability issue.

**Comment by mjbrisebois** [comment]
cc @zo-el 

Thanks to you catching the initial sign-up error, I was able to find the problem.  The wormhole payloads were switched to base64 data and I have not updated Chaperone to decode it yet.

I need to find out why sign-up only fails the first time when it should fail every time.

**Pull request merged**
