### PR TITLE
Dummy dna

### PR DESCRIPTION
**Pull request by zo-el**

### CODE REVIEW

**Comment by mjbrisebois** [comment]
I like this idea of having a dummy DNA, but I'm not sure if we want it to be in the Envoy repo.  It would be useful to have this for Chaperone HCC mode tests as well.

cc @zo-el

**Comment by zo-el** [comment]
> I like this idea of having a dummy DNA, but I'm not sure if we want it to be in the Envoy repo. It would be useful to have this for Chaperone HCC mode tests as well.
> 
> cc @zo-el

@mjbrisebois Would you want this to be in a different repo? Then you would have to make releases for the dummy DNA!

**Comment by mjbrisebois** [comment]
> @mjbrisebois Would you want this to be in a different repo? Then you would have to make releases for the dummy DNA!

Yes, a different repo.

Everything goes through a release process.  It's easier to do that in an isolated context than one where it has attached dependencies.  The choice isn't whether we do releases, it is where we put the upstream dependency in a 1-many relationship.

**Comment by zo-el** [comment]
Here is a link to the `dummy-dna` repo: https://github.com/Holo-Host/dummy-dna

**Pull request closed without merging**
