### PR TITLE
Call ActivateApp if zome call or appInfo fails with CellMissing

### PR DESCRIPTION
**Pull request by timotree3**
Depends on #101 due to using the new mock-conductor feature

### CODE REVIEW

**Comment by timotree3** [comment]
Converting to draft while trying to get tests passing

**Review by zo-el — APPROVED** [review]
Nice work. I'll test it out on an hpos.

**Comment by timotree3** [comment]
Cool. Did you see #101 as well which this depends on?

**Comment by zo-el** [comment]
Just approved it. Lets get these tests running and then merge it

**Pull request merged**
